[window]
decorations = "full"
opacity = 0.8
dynamic_title = true

  [window.dimensions]
  columns = 140
  lines = 38

[font]
size = 14
  [font.normal]
  family = "JetBrainsMono Nerd Font"
  style = "Regular"

  [font.offset]
  x = 0
  y = 0

  [font.glyph_offset]
  x = 0
  y = 0

[shell]
		program = "/opt/homebrew/bin/fish"

[scrolling]
history = 10_000
multiplier = 3

[cursor]
style = "Underline"
unfocused_hollow = true

[colors.primary]
background = "#000000"
foreground = "#b6b6b6"

[colors.normal]
black = "#000000"
green = "#00a600"
yellow = "#999900"
magenta = "#b200b2"
cyan = "#00a6b2"
white = "#bfbfbf"

[colors.bright]
black = "#666666"
green = "#00d900"
yellow = "#e5e500"
magenta = "#e500e5"
cyan = "#00e5e5"
white = "#e5e5e5"

# [[keyboard.bindings]]
# key = "N"
# mods = "Command"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "Back"
mods = "Option"
chars = "\u001b"

[[keyboard.bindings]]
key = "Right"
mods = "Option"
chars = "\u001bF"
[[keyboard.bindings]]
key = "Left"
mods = "Option"
chars = "\u001bB"
